//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFunc.Maths.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xFunc.Maths.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse assignment key..
        /// </summary>
        internal static string AssignKeyParseException {
            get {
                return ResourceManager.GetString("AssignKeyParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;)&apos; symbol is expected after &apos;{0}&apos; expression..
        /// </summary>
        internal static string CloseParenParseException {
            get {
                return ResourceManager.GetString("CloseParenParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comma symbol (&apos;,&apos;) is expected after &apos;{0}&apos; expression..
        /// </summary>
        internal static string CommaParseException {
            get {
                return ResourceManager.GetString("CommaParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t change constants..
        /// </summary>
        internal static string ConstError {
            get {
                return ResourceManager.GetString("ConstError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse value of &apos;def&apos; expression..
        /// </summary>
        internal static string DefValueParseException {
            get {
                return ResourceManager.GetString("DefValueParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;°&apos; symbol is required in polar complex number form..
        /// </summary>
        internal static string DegreeComplexNumberParseException {
            get {
                return ResourceManager.GetString("DegreeComplexNumberParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter #{2} has wrong type (Expected: {0}; Actual: {1})..
        /// </summary>
        internal static string DifferentParameterTypeMismatchExceptionError {
            get {
                return ResourceManager.GetString("DifferentParameterTypeMismatchExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain is invalid..
        /// </summary>
        internal static string DomainIsInvalid {
            get {
                return ResourceManager.GetString("DomainIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of added ranges exceeded the amount specified on the builder creation..
        /// </summary>
        internal static string DomainRangeExceeded {
            get {
                return ResourceManager.GetString("DomainRangeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain range is incorrect..
        /// </summary>
        internal static string DomainRangeIsIncorrect {
            get {
                return ResourceManager.GetString("DomainRangeIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;start&apos; parameter is greater than &apos;end&apos;..
        /// </summary>
        internal static string DomainRangeStartIsGreaterThanEnd {
            get {
                return ResourceManager.GetString("DomainRangeStartIsGreaterThanEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; parameter is already present in the lambda..
        /// </summary>
        internal static string DuplidateLambdaParameterParseException {
            get {
                return ResourceManager.GetString("DuplidateLambdaParameterParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing the tree..
        /// </summary>
        internal static string ErrorWhileParsingTree {
            get {
                return ResourceManager.GetString("ErrorWhileParsingTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse an exponent..
        /// </summary>
        internal static string ExponentParseException {
            get {
                return ResourceManager.GetString("ExponentParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse body of &apos;for&apos; expression..
        /// </summary>
        internal static string ForBodyParseException {
            get {
                return ResourceManager.GetString("ForBodyParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse condition of &apos;for&apos; expression..
        /// </summary>
        internal static string ForConditionParseException {
            get {
                return ResourceManager.GetString("ForConditionParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse initializer of &apos;for&apos; expression..
        /// </summary>
        internal static string ForInitParseException {
            get {
                return ResourceManager.GetString("ForInitParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse iterator of &apos;for&apos; expression..
        /// </summary>
        internal static string ForIterParseException {
            get {
                return ResourceManager.GetString("ForIterParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;)&apos; symbol is expected at the end of &apos;{0}&apos; definition..
        /// </summary>
        internal static string FunctionCloseParenthesisParseException {
            get {
                return ResourceManager.GetString("FunctionCloseParenthesisParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;(&apos; symbol is expected after &apos;{0}&apos; definition..
        /// </summary>
        internal static string FunctionOpenParenthesisParseException {
            get {
                return ResourceManager.GetString("FunctionOpenParenthesisParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse condition of &apos;if&apos; expression..
        /// </summary>
        internal static string IfConditionParseException {
            get {
                return ResourceManager.GetString("IfConditionParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse &apos;else&apos; statement of &apos;if&apos; expression..
        /// </summary>
        internal static string IfElseParseException {
            get {
                return ResourceManager.GetString("IfElseParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse &apos;then&apos; statement of &apos;if&apos; expression..
        /// </summary>
        internal static string IfThenParseException {
            get {
                return ResourceManager.GetString("IfThenParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left parameter has wrong type (Expected: {0}; Actual: {1})..
        /// </summary>
        internal static string LeftParameterTypeMismatchExceptionError {
            get {
                return ResourceManager.GetString("LeftParameterTypeMismatchExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of parameters is less than expected..
        /// </summary>
        internal static string LessParams {
            get {
                return ResourceManager.GetString("LessParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of matrices is invalid..
        /// </summary>
        internal static string MatrixArgException {
            get {
                return ResourceManager.GetString("MatrixArgException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix declaration should end with the &apos;}&apos; symbol..
        /// </summary>
        internal static string MatrixCloseBraceParseException {
            get {
                return ResourceManager.GetString("MatrixCloseBraceParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressions in matrix should be separated by the &apos;,&apos; symbol..
        /// </summary>
        internal static string MatrixCommaParseException {
            get {
                return ResourceManager.GetString("MatrixCommaParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse an expression after the comma symbol..
        /// </summary>
        internal static string MissingExpParseException {
            get {
                return ResourceManager.GetString("MissingExpParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t parse the body of the lambda expression..
        /// </summary>
        internal static string MissingLambdaBodyParseException {
            get {
                return ResourceManager.GetString("MissingLambdaBodyParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lambda operator (&apos;=&gt;&apos;) is missng..
        /// </summary>
        internal static string MissingLambdaParseException {
            get {
                return ResourceManager.GetString("MissingLambdaParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of parameters is more than expected..
        /// </summary>
        internal static string MoreParams {
            get {
                return ResourceManager.GetString("MoreParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function is not specified..
        /// </summary>
        internal static string NotSpecifiedFunction {
            get {
                return ResourceManager.GetString("NotSpecifiedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string NotSupportedSymbol {
            get {
                return ResourceManager.GetString("NotSupportedSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter list should end with &apos;)&apos; symbol..
        /// </summary>
        internal static string ParameterListCloseParseException {
            get {
                return ResourceManager.GetString("ParameterListCloseParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter type mismatch (Expected: {0}; Actual: {1})..
        /// </summary>
        internal static string ParameterTypeMismatchExceptionError {
            get {
                return ResourceManager.GetString("ParameterTypeMismatchExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phase of complex number is expected after the &apos;∠&apos; symbol..
        /// </summary>
        internal static string PhaseParseException {
            get {
                return ResourceManager.GetString("PhaseParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot change the read-only variable..
        /// </summary>
        internal static string ReadOnlyError {
            get {
                return ResourceManager.GetString("ReadOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of evaluation is not supported (&apos;{0}&apos;)..
        /// </summary>
        internal static string ResultIsNotSupported {
            get {
                return ResourceManager.GetString("ResultIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right parameter has wrong type (Expected: {0}; Actual: {1})..
        /// </summary>
        internal static string RightParameterTypeMismatchExceptionError {
            get {
                return ResourceManager.GetString("RightParameterTypeMismatchExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse second operand of &apos;{0}&apos; operator..
        /// </summary>
        internal static string SecondOperandParseException {
            get {
                return ResourceManager.GetString("SecondOperandParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the end of string expression..
        /// </summary>
        internal static string StringTokenizeException {
            get {
                return ResourceManager.GetString("StringTokenizeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;:&apos; symbol is expected &apos;then&apos; expression..
        /// </summary>
        internal static string TernaryColonParseException {
            get {
                return ResourceManager.GetString("TernaryColonParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse &apos;else&apos; statement of ternary operator..
        /// </summary>
        internal static string TernaryElseParseException {
            get {
                return ResourceManager.GetString("TernaryElseParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse &apos;then&apos; statement of ternary operator..
        /// </summary>
        internal static string TernaryThenParseException {
            get {
                return ResourceManager.GetString("TernaryThenParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; unit is not supported..
        /// </summary>
        internal static string UnitIsNotSupportedException {
            get {
                return ResourceManager.GetString("UnitIsNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not an integer..
        /// </summary>
        internal static string ValueIsNotInteger {
            get {
                return ResourceManager.GetString("ValueIsNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0} ({1})&apos; conversion value is not supported..
        /// </summary>
        internal static string ValueIsNotSupportedException {
            get {
                return ResourceManager.GetString("ValueIsNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; variable not found..
        /// </summary>
        internal static string VariableNotFoundExceptionError {
            get {
                return ResourceManager.GetString("VariableNotFoundExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vector declaration should end with the &apos;}&apos; symbol..
        /// </summary>
        internal static string VectorCloseBraceParseException {
            get {
                return ResourceManager.GetString("VectorCloseBraceParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressions in vector should be separated by the &apos;,&apos; symbol..
        /// </summary>
        internal static string VectorCommaParseException {
            get {
                return ResourceManager.GetString("VectorCommaParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of vector should equal to 3..
        /// </summary>
        internal static string VectorCrossException {
            get {
                return ResourceManager.GetString("VectorCrossException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vector should not be empty..
        /// </summary>
        internal static string VectorEmptyError {
            get {
                return ResourceManager.GetString("VectorEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse body of &apos;while&apos; expression..
        /// </summary>
        internal static string WhileBodyParseException {
            get {
                return ResourceManager.GetString("WhileBodyParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse condition of &apos;while&apos; expression..
        /// </summary>
        internal static string WhileConditionParseException {
            get {
                return ResourceManager.GetString("WhileConditionParseException", resourceCulture);
            }
        }
    }
}
