//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFunc.Maths.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xFunc.Maths.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &apos;{1}&apos; was assigned to the function &apos;{0}&apos;..
        /// </summary>
        internal static string AssignFunction {
            get {
                return ResourceManager.GetString("AssignFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{1}&apos; was assigned to the variable &apos;{0}&apos;..
        /// </summary>
        internal static string AssignVariable {
            get {
                return ResourceManager.GetString("AssignVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t change constants..
        /// </summary>
        internal static string ConstError {
            get {
                return ResourceManager.GetString("ConstError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing the tree..
        /// </summary>
        internal static string ErrorWhileParsingTree {
            get {
                return ResourceManager.GetString("ErrorWhileParsingTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &apos;{0}&apos; has an invalid format..
        /// </summary>
        internal static string FormatException {
            get {
                return ResourceManager.GetString("FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; function not found..
        /// </summary>
        internal static string FunctionNotFoundExceptionError {
            get {
                return ResourceManager.GetString("FunctionNotFoundExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression is invalid..
        /// </summary>
        internal static string InvalidExpression {
            get {
                return ResourceManager.GetString("InvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function has an invalid number of variables..
        /// </summary>
        internal static string InvalidNumberOfVariables {
            get {
                return ResourceManager.GetString("InvalidNumberOfVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of parameters is less than expected..
        /// </summary>
        internal static string LessParams {
            get {
                return ResourceManager.GetString("LessParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of matrices is invalid..
        /// </summary>
        internal static string MatrixArgException {
            get {
                return ResourceManager.GetString("MatrixArgException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of parameters is more than expected..
        /// </summary>
        internal static string MoreParams {
            get {
                return ResourceManager.GetString("MoreParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brackets are not balanced..
        /// </summary>
        internal static string NotBalanced {
            get {
                return ResourceManager.GetString("NotBalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough parameters..
        /// </summary>
        internal static string NotEnoughParams {
            get {
                return ResourceManager.GetString("NotEnoughParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function is not specified..
        /// </summary>
        internal static string NotSpecifiedFunction {
            get {
                return ResourceManager.GetString("NotSpecifiedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string NotSupportedSymbol {
            get {
                return ResourceManager.GetString("NotSupportedSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter type mismatch (Expected: {0}; Actual: {1})..
        /// </summary>
        internal static string ParameterTypeMismatchExceptionError {
            get {
                return ResourceManager.GetString("ParameterTypeMismatchExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot change value of &quot;{0}&quot;..
        /// </summary>
        internal static string ReadOnlyError {
            get {
                return ResourceManager.GetString("ReadOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; function is removed..
        /// </summary>
        internal static string UndefineFunction {
            get {
                return ResourceManager.GetString("UndefineFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; variable is removed..
        /// </summary>
        internal static string UndefineVariable {
            get {
                return ResourceManager.GetString("UndefineVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error..
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; variable not found..
        /// </summary>
        internal static string VariableNotFoundExceptionError {
            get {
                return ResourceManager.GetString("VariableNotFoundExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of vector should equal to 3..
        /// </summary>
        internal static string VectorCrossException {
            get {
                return ResourceManager.GetString("VectorCrossException", resourceCulture);
            }
        }
    }
}
