//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFunc.Maths.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("xFunc.Maths.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ConstError {
            get {
                return ResourceManager.GetString("ConstError", resourceCulture);
            }
        }
        
        internal static string ErrorWhileParsingTree {
            get {
                return ResourceManager.GetString("ErrorWhileParsingTree", resourceCulture);
            }
        }
        
        internal static string LessParams {
            get {
                return ResourceManager.GetString("LessParams", resourceCulture);
            }
        }
        
        internal static string MatrixArgException {
            get {
                return ResourceManager.GetString("MatrixArgException", resourceCulture);
            }
        }
        
        internal static string MoreParams {
            get {
                return ResourceManager.GetString("MoreParams", resourceCulture);
            }
        }
        
        internal static string NotSpecifiedFunction {
            get {
                return ResourceManager.GetString("NotSpecifiedFunction", resourceCulture);
            }
        }
        
        internal static string NotSupportedSymbol {
            get {
                return ResourceManager.GetString("NotSupportedSymbol", resourceCulture);
            }
        }
        
        internal static string ReadOnlyError {
            get {
                return ResourceManager.GetString("ReadOnlyError", resourceCulture);
            }
        }
        
        internal static string VariableNotFoundExceptionError {
            get {
                return ResourceManager.GetString("VariableNotFoundExceptionError", resourceCulture);
            }
        }
        
        internal static string ParameterTypeMismatchExceptionError {
            get {
                return ResourceManager.GetString("ParameterTypeMismatchExceptionError", resourceCulture);
            }
        }
        
        internal static string VectorCrossException {
            get {
                return ResourceManager.GetString("VectorCrossException", resourceCulture);
            }
        }
        
        internal static string DifferentParameterTypeMismatchExceptionError {
            get {
                return ResourceManager.GetString("DifferentParameterTypeMismatchExceptionError", resourceCulture);
            }
        }
        
        internal static string LeftParameterTypeMismatchExceptionError {
            get {
                return ResourceManager.GetString("LeftParameterTypeMismatchExceptionError", resourceCulture);
            }
        }
        
        internal static string RightParameterTypeMismatchExceptionError {
            get {
                return ResourceManager.GetString("RightParameterTypeMismatchExceptionError", resourceCulture);
            }
        }
        
        internal static string MatrixCloseBraceParseException {
            get {
                return ResourceManager.GetString("MatrixCloseBraceParseException", resourceCulture);
            }
        }
        
        internal static string MatrixCommaParseException {
            get {
                return ResourceManager.GetString("MatrixCommaParseException", resourceCulture);
            }
        }
        
        internal static string VectorCloseBraceParseException {
            get {
                return ResourceManager.GetString("VectorCloseBraceParseException", resourceCulture);
            }
        }
        
        internal static string VectorCommaParseException {
            get {
                return ResourceManager.GetString("VectorCommaParseException", resourceCulture);
            }
        }
        
        internal static string PhaseParseException {
            get {
                return ResourceManager.GetString("PhaseParseException", resourceCulture);
            }
        }
        
        internal static string DegreeComplexNumberParseException {
            get {
                return ResourceManager.GetString("DegreeComplexNumberParseException", resourceCulture);
            }
        }
        
        internal static string ExponentParseException {
            get {
                return ResourceManager.GetString("ExponentParseException", resourceCulture);
            }
        }
        
        internal static string SecondOperandParseException {
            get {
                return ResourceManager.GetString("SecondOperandParseException", resourceCulture);
            }
        }
        
        internal static string FunctionOpenParenthesisParseException {
            get {
                return ResourceManager.GetString("FunctionOpenParenthesisParseException", resourceCulture);
            }
        }
        
        internal static string FunctionCloseParenthesisParseException {
            get {
                return ResourceManager.GetString("FunctionCloseParenthesisParseException", resourceCulture);
            }
        }
        
        internal static string AssignKeyParseException {
            get {
                return ResourceManager.GetString("AssignKeyParseException", resourceCulture);
            }
        }
        
        internal static string DefValueParseException {
            get {
                return ResourceManager.GetString("DefValueParseException", resourceCulture);
            }
        }
        
        internal static string IfConditionParseException {
            get {
                return ResourceManager.GetString("IfConditionParseException", resourceCulture);
            }
        }
        
        internal static string IfThenParseException {
            get {
                return ResourceManager.GetString("IfThenParseException", resourceCulture);
            }
        }
        
        internal static string IfElseParseException {
            get {
                return ResourceManager.GetString("IfElseParseException", resourceCulture);
            }
        }
        
        internal static string ForBodyParseException {
            get {
                return ResourceManager.GetString("ForBodyParseException", resourceCulture);
            }
        }
        
        internal static string ForInitParseException {
            get {
                return ResourceManager.GetString("ForInitParseException", resourceCulture);
            }
        }
        
        internal static string ForConditionParseException {
            get {
                return ResourceManager.GetString("ForConditionParseException", resourceCulture);
            }
        }
        
        internal static string ForIterParseException {
            get {
                return ResourceManager.GetString("ForIterParseException", resourceCulture);
            }
        }
        
        internal static string WhileBodyParseException {
            get {
                return ResourceManager.GetString("WhileBodyParseException", resourceCulture);
            }
        }
        
        internal static string WhileConditionParseException {
            get {
                return ResourceManager.GetString("WhileConditionParseException", resourceCulture);
            }
        }
        
        internal static string CommaParseException {
            get {
                return ResourceManager.GetString("CommaParseException", resourceCulture);
            }
        }
        
        internal static string CloseParenParseException {
            get {
                return ResourceManager.GetString("CloseParenParseException", resourceCulture);
            }
        }
        
        internal static string ParameterListCloseParseException {
            get {
                return ResourceManager.GetString("ParameterListCloseParseException", resourceCulture);
            }
        }
        
        internal static string ResultIsNotSupported {
            get {
                return ResourceManager.GetString("ResultIsNotSupported", resourceCulture);
            }
        }
        
        internal static string ValueIsNotInteger {
            get {
                return ResourceManager.GetString("ValueIsNotInteger", resourceCulture);
            }
        }
        
        internal static string TernaryThenParseException {
            get {
                return ResourceManager.GetString("TernaryThenParseException", resourceCulture);
            }
        }
        
        internal static string TernaryElseParseException {
            get {
                return ResourceManager.GetString("TernaryElseParseException", resourceCulture);
            }
        }
        
        internal static string TernaryColonParseException {
            get {
                return ResourceManager.GetString("TernaryColonParseException", resourceCulture);
            }
        }
        
        internal static string VectorEmptyError {
            get {
                return ResourceManager.GetString("VectorEmptyError", resourceCulture);
            }
        }
        
        internal static string MissingExpParseException {
            get {
                return ResourceManager.GetString("MissingExpParseException", resourceCulture);
            }
        }
        
        internal static string StringTokenizeException {
            get {
                return ResourceManager.GetString("StringTokenizeException", resourceCulture);
            }
        }
        
        internal static string UnitIsNotSupportedException {
            get {
                return ResourceManager.GetString("UnitIsNotSupportedException", resourceCulture);
            }
        }
        
        internal static string ValueIsNotSupportedException {
            get {
                return ResourceManager.GetString("ValueIsNotSupportedException", resourceCulture);
            }
        }
        
        internal static string MissingLambdaParseException {
            get {
                return ResourceManager.GetString("MissingLambdaParseException", resourceCulture);
            }
        }
        
        internal static string DuplidateLambdaParameterParseException {
            get {
                return ResourceManager.GetString("DuplidateLambdaParameterParseException", resourceCulture);
            }
        }
        
        internal static string MissingLambdaBodyParseException {
            get {
                return ResourceManager.GetString("MissingLambdaBodyParseException", resourceCulture);
            }
        }
    }
}
