//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFunc.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xFunc.App.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string aboutMenu {
            get {
                return ResourceManager.GetString("aboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Answer:.
        /// </summary>
        public static string answerLabel {
            get {
                return ResourceManager.GetString("answerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dmitry Kischenko.
        /// </summary>
        public static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string authorText {
            get {
                return ResourceManager.GetString("authorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sovle.
        /// </summary>
        public static string calcButton {
            get {
                return ResourceManager.GetString("calcButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string cm {
            get {
                return ResourceManager.GetString("cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string copyMenu {
            get {
                return ResourceManager.GetString("copyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string cutMenu {
            get {
                return ResourceManager.GetString("cutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string degreeMenu {
            get {
                return ResourceManager.GetString("degreeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string editMenu {
            get {
                return ResourceManager.GetString("editMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Function:.
        /// </summary>
        public static string functionLabel {
            get {
                return ResourceManager.GetString("functionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradian.
        /// </summary>
        public static string gradianMenu {
            get {
                return ResourceManager.GetString("gradianMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string helpMenu {
            get {
                return ResourceManager.GetString("helpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page:.
        /// </summary>
        public static string homePageText {
            get {
                return ResourceManager.GetString("homePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perhaps, variables have entered incorrectly..
        /// </summary>
        public static string indexOutOfRangeexceptionMessage {
            get {
                return ResourceManager.GetString("indexOutOfRangeexceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable not found..
        /// </summary>
        public static string keyNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("keyNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical.
        /// </summary>
        public static string logicLabel {
            get {
                return ResourceManager.GetString("logicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported statements:
        ///
        ///! (not) - negation;
        ///&amp; (and) - logical conjunction;
        ///| (or) - logical disjunction;
        ///-&gt;, =&gt; (impl) - logical implication
        ///&lt;-&gt;, &lt;=&gt; (eq) - logically equivalent;
        ///nand - Sheffer stroke;
        ///nor - Peirce arrow;
        ///^, xor - exclusive disjunction;
        ///table(x) - truth table;
        ///t, true - true;
        ///f, false - false;.
        /// </summary>
        public static string logicToolTip {
            get {
                return ResourceManager.GetString("logicToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truth table.
        /// </summary>
        public static string logicViewTitle {
            get {
                return ResourceManager.GetString("logicViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathematical.
        /// </summary>
        public static string mathLabel {
            get {
                return ResourceManager.GetString("mathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported statements:
        ///
        ///+ - addition;
        ///- - subtraction, unary minus;
        ///* - multiplication;
        //// - division;
        ///^ - involution;
        ///abs(x) - absolute;
        ///sin(x) - sine;
        ///cos(x) - cosine;
        ///tan(x) - tangent;
        ///cot(x) - cotangent;
        ///arcsin(x) - arcsine;
        ///arccos(x) - aarccosine;
        ///arctan(x) - arctangent;
        ///arccot(x) - arccotangent;
        ///sqrt(x) - square root;
        ///root(x, n) - nth root;
        ///lg(x) - common logarithm;
        ///ln(x) - natural logarithm;
        ///log(x, y) - logarithm;
        ///exp(x) - exponential;
        ///pi - Pi constant;
        ///plot(x) - graph;
        ///deriv(x) [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mathToolTip {
            get {
                return ResourceManager.GetString("mathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not supported..
        /// </summary>
        public static string notSupported {
            get {
                return ResourceManager.GetString("notSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute value.
        /// </summary>
        public static string operationAbs {
            get {
                return ResourceManager.GetString("operationAbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string operationAnd {
            get {
                return ResourceManager.GetString("operationAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arccosine.
        /// </summary>
        public static string operationArccos {
            get {
                return ResourceManager.GetString("operationArccos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arccotangent.
        /// </summary>
        public static string operationArccot {
            get {
                return ResourceManager.GetString("operationArccot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcsine.
        /// </summary>
        public static string operationArcsin {
            get {
                return ResourceManager.GetString("operationArcsin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arctangent.
        /// </summary>
        public static string operationArctan {
            get {
                return ResourceManager.GetString("operationArctan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosine.
        /// </summary>
        public static string operationCos {
            get {
                return ResourceManager.GetString("operationCos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotangent.
        /// </summary>
        public static string operationCot {
            get {
                return ResourceManager.GetString("operationCot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivative.
        /// </summary>
        public static string operationDeriv {
            get {
                return ResourceManager.GetString("operationDeriv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string operationDiv {
            get {
                return ResourceManager.GetString("operationDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equality.
        /// </summary>
        public static string operationEq {
            get {
                return ResourceManager.GetString("operationEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponent.
        /// </summary>
        public static string operationExp {
            get {
                return ResourceManager.GetString("operationExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False constant.
        /// </summary>
        public static string operationFalse {
            get {
                return ResourceManager.GetString("operationFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implication.
        /// </summary>
        public static string operationImpl {
            get {
                return ResourceManager.GetString("operationImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponentiation.
        /// </summary>
        public static string operationInv {
            get {
                return ResourceManager.GetString("operationInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common logarithm.
        /// </summary>
        public static string operationLg {
            get {
                return ResourceManager.GetString("operationLg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural logarithm.
        /// </summary>
        public static string operationLn {
            get {
                return ResourceManager.GetString("operationLn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarithm.
        /// </summary>
        public static string operationLog {
            get {
                return ResourceManager.GetString("operationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtraction.
        /// </summary>
        public static string operationMinus {
            get {
                return ResourceManager.GetString("operationMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication.
        /// </summary>
        public static string operationMul {
            get {
                return ResourceManager.GetString("operationMul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheffer stroke.
        /// </summary>
        public static string operationNAnd {
            get {
                return ResourceManager.GetString("operationNAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peirce&apos;s arrow.
        /// </summary>
        public static string operationNOr {
            get {
                return ResourceManager.GetString("operationNOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        public static string operationNot {
            get {
                return ResourceManager.GetString("operationNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string operationOr {
            get {
                return ResourceManager.GetString("operationOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi.
        /// </summary>
        public static string operationPi {
            get {
                return ResourceManager.GetString("operationPi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph of a function.
        /// </summary>
        public static string operationPlot {
            get {
                return ResourceManager.GetString("operationPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        public static string operationPlus {
            get {
                return ResourceManager.GetString("operationPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n-th root.
        /// </summary>
        public static string operationRoot {
            get {
                return ResourceManager.GetString("operationRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine.
        /// </summary>
        public static string operationSin {
            get {
                return ResourceManager.GetString("operationSin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string operationsMenu {
            get {
                return ResourceManager.GetString("operationsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string operationSqr {
            get {
                return ResourceManager.GetString("operationSqr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square root.
        /// </summary>
        public static string operationSqrt {
            get {
                return ResourceManager.GetString("operationSqrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string operationsTitle {
            get {
                return ResourceManager.GetString("operationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truth Table.
        /// </summary>
        public static string operationTable {
            get {
                return ResourceManager.GetString("operationTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangent.
        /// </summary>
        public static string operationTan {
            get {
                return ResourceManager.GetString("operationTan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True constant.
        /// </summary>
        public static string operationTrue {
            get {
                return ResourceManager.GetString("operationTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive or.
        /// </summary>
        public static string operationXOr {
            get {
                return ResourceManager.GetString("operationXOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string pasteMenu {
            get {
                return ResourceManager.GetString("pasteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radian.
        /// </summary>
        public static string radianMenu {
            get {
                return ResourceManager.GetString("radianMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string redoMenu {
            get {
                return ResourceManager.GetString("redoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string selectAllMenu {
            get {
                return ResourceManager.GetString("selectAllMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Grid.
        /// </summary>
        public static string showGridBox {
            get {
                return ResourceManager.GetString("showGridBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string undoMenu {
            get {
                return ResourceManager.GetString("undoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Variables:.
        /// </summary>
        public static string varsLabel {
            get {
                return ResourceManager.GetString("varsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string versionText {
            get {
                return ResourceManager.GetString("versionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string viewMenu {
            get {
                return ResourceManager.GetString("viewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computation....
        /// </summary>
        public static string workingStatus {
            get {
                return ResourceManager.GetString("workingStatus", resourceCulture);
            }
        }
    }
}
