//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFunc.UnitConverters.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xFunc.UnitConverters.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acres.
        /// </summary>
        internal static string Acres {
            get {
                return ResourceManager.GetString("Acres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string AreaConverterName {
            get {
                return ResourceManager.GetString("AreaConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hectares.
        /// </summary>
        internal static string Hectares {
            get {
                return ResourceManager.GetString("Hectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string LengthConverterName {
            get {
                return ResourceManager.GetString("LengthConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        internal static string MassConverterName {
            get {
                return ResourceManager.GetString("MassConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string PowerConverterName {
            get {
                return ResourceManager.GetString("PowerConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square centimeters.
        /// </summary>
        internal static string SquareCentimeters {
            get {
                return ResourceManager.GetString("SquareCentimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square feet.
        /// </summary>
        internal static string SquareFeet {
            get {
                return ResourceManager.GetString("SquareFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square inches.
        /// </summary>
        internal static string SquareInches {
            get {
                return ResourceManager.GetString("SquareInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square kilometers.
        /// </summary>
        internal static string SquareKilometers {
            get {
                return ResourceManager.GetString("SquareKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square metres.
        /// </summary>
        internal static string SquareMetres {
            get {
                return ResourceManager.GetString("SquareMetres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square miles.
        /// </summary>
        internal static string SquareMiles {
            get {
                return ResourceManager.GetString("SquareMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square millimeters.
        /// </summary>
        internal static string SquareMillimeters {
            get {
                return ResourceManager.GetString("SquareMillimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square yards.
        /// </summary>
        internal static string SquareYards {
            get {
                return ResourceManager.GetString("SquareYards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string TemperatureConverterName {
            get {
                return ResourceManager.GetString("TemperatureConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string TimeConverterName {
            get {
                return ResourceManager.GetString("TimeConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string VolumeConverterName {
            get {
                return ResourceManager.GetString("VolumeConverterName", resourceCulture);
            }
        }
    }
}
