//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFunc.UnitConverters.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xFunc.UnitConverters.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acres.
        /// </summary>
        internal static string Acres {
            get {
                return ResourceManager.GetString("Acres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string AreaConverterName {
            get {
                return ResourceManager.GetString("AreaConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AstronomicalUnits.
        /// </summary>
        internal static string AstronomicalUnits {
            get {
                return ResourceManager.GetString("AstronomicalUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        internal static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeters.
        /// </summary>
        internal static string Centimeters {
            get {
                return ResourceManager.GetString("Centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chains.
        /// </summary>
        internal static string Chains {
            get {
                return ResourceManager.GetString("Chains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic centimeters.
        /// </summary>
        internal static string CubicCentimeters {
            get {
                return ResourceManager.GetString("CubicCentimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic feet.
        /// </summary>
        internal static string CubicFeet {
            get {
                return ResourceManager.GetString("CubicFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic inches.
        /// </summary>
        internal static string CubicInches {
            get {
                return ResourceManager.GetString("CubicInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic meters.
        /// </summary>
        internal static string CubicMeters {
            get {
                return ResourceManager.GetString("CubicMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic yards.
        /// </summary>
        internal static string CubicYards {
            get {
                return ResourceManager.GetString("CubicYards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delisle.
        /// </summary>
        internal static string Delisle {
            get {
                return ResourceManager.GetString("Delisle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        internal static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fathoms.
        /// </summary>
        internal static string Fathoms {
            get {
                return ResourceManager.GetString("Fathoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallons (UK).
        /// </summary>
        internal static string GallonsUK {
            get {
                return ResourceManager.GetString("GallonsUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallons (US).
        /// </summary>
        internal static string GallonsUS {
            get {
                return ResourceManager.GetString("GallonsUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grams.
        /// </summary>
        internal static string Grams {
            get {
                return ResourceManager.GetString("Grams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hectares.
        /// </summary>
        internal static string Hectares {
            get {
                return ResourceManager.GetString("Hectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horsepower.
        /// </summary>
        internal static string Horsepower {
            get {
                return ResourceManager.GetString("Horsepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        internal static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelvin.
        /// </summary>
        internal static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilograms.
        /// </summary>
        internal static string Kilograms {
            get {
                return ResourceManager.GetString("Kilograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        internal static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilowatts.
        /// </summary>
        internal static string Kilowatts {
            get {
                return ResourceManager.GetString("Kilowatts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string LengthConverterName {
            get {
                return ResourceManager.GetString("LengthConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightYears.
        /// </summary>
        internal static string LightYears {
            get {
                return ResourceManager.GetString("LightYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litres.
        /// </summary>
        internal static string Litres {
            get {
                return ResourceManager.GetString("Litres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        internal static string MassConverterName {
            get {
                return ResourceManager.GetString("MassConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metres.
        /// </summary>
        internal static string Metres {
            get {
                return ResourceManager.GetString("Metres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micrometers.
        /// </summary>
        internal static string Micrometers {
            get {
                return ResourceManager.GetString("Micrometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microseconds.
        /// </summary>
        internal static string Microseconds {
            get {
                return ResourceManager.GetString("Microseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        internal static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milligrams.
        /// </summary>
        internal static string Milligrams {
            get {
                return ResourceManager.GetString("Milligrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimeters.
        /// </summary>
        internal static string Millimeters {
            get {
                return ResourceManager.GetString("Millimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds.
        /// </summary>
        internal static string Milliseconds {
            get {
                return ResourceManager.GetString("Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nanometres.
        /// </summary>
        internal static string Nanometres {
            get {
                return ResourceManager.GetString("Nanometres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NauticalMiles.
        /// </summary>
        internal static string NauticalMiles {
            get {
                return ResourceManager.GetString("NauticalMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newton.
        /// </summary>
        internal static string Newton {
            get {
                return ResourceManager.GetString("Newton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsecs.
        /// </summary>
        internal static string Parsecs {
            get {
                return ResourceManager.GetString("Parsecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pints (UK).
        /// </summary>
        internal static string PintsUK {
            get {
                return ResourceManager.GetString("PintsUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pints (US).
        /// </summary>
        internal static string PintsUS {
            get {
                return ResourceManager.GetString("PintsUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds.
        /// </summary>
        internal static string Pounds {
            get {
                return ResourceManager.GetString("Pounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string PowerConverterName {
            get {
                return ResourceManager.GetString("PowerConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankine.
        /// </summary>
        internal static string Rankine {
            get {
                return ResourceManager.GetString("Rankine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réaumur.
        /// </summary>
        internal static string Réaumur {
            get {
                return ResourceManager.GetString("Réaumur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rods.
        /// </summary>
        internal static string Rods {
            get {
                return ResourceManager.GetString("Rods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rømer.
        /// </summary>
        internal static string Rømer {
            get {
                return ResourceManager.GetString("Rømer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slugs.
        /// </summary>
        internal static string Slugs {
            get {
                return ResourceManager.GetString("Slugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square centimeters.
        /// </summary>
        internal static string SquareCentimeters {
            get {
                return ResourceManager.GetString("SquareCentimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square feet.
        /// </summary>
        internal static string SquareFeet {
            get {
                return ResourceManager.GetString("SquareFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square inches.
        /// </summary>
        internal static string SquareInches {
            get {
                return ResourceManager.GetString("SquareInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square kilometers.
        /// </summary>
        internal static string SquareKilometers {
            get {
                return ResourceManager.GetString("SquareKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square metres.
        /// </summary>
        internal static string SquareMetres {
            get {
                return ResourceManager.GetString("SquareMetres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square miles.
        /// </summary>
        internal static string SquareMiles {
            get {
                return ResourceManager.GetString("SquareMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square millimeters.
        /// </summary>
        internal static string SquareMillimeters {
            get {
                return ResourceManager.GetString("SquareMillimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square yards.
        /// </summary>
        internal static string SquareYards {
            get {
                return ResourceManager.GetString("SquareYards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string TemperatureConverterName {
            get {
                return ResourceManager.GetString("TemperatureConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string TimeConverterName {
            get {
                return ResourceManager.GetString("TimeConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonne.
        /// </summary>
        internal static string Tonne {
            get {
                return ResourceManager.GetString("Tonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string VolumeConverterName {
            get {
                return ResourceManager.GetString("VolumeConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watts.
        /// </summary>
        internal static string Watts {
            get {
                return ResourceManager.GetString("Watts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yards.
        /// </summary>
        internal static string Yards {
            get {
                return ResourceManager.GetString("Yards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
