//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFunc.UnitConverters.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("xFunc.UnitConverters.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Acres {
            get {
                return ResourceManager.GetString("Acres", resourceCulture);
            }
        }
        
        internal static string AreaConverterName {
            get {
                return ResourceManager.GetString("AreaConverterName", resourceCulture);
            }
        }
        
        internal static string AstronomicalUnits {
            get {
                return ResourceManager.GetString("AstronomicalUnits", resourceCulture);
            }
        }
        
        internal static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        internal static string Centimeters {
            get {
                return ResourceManager.GetString("Centimeters", resourceCulture);
            }
        }
        
        internal static string Chains {
            get {
                return ResourceManager.GetString("Chains", resourceCulture);
            }
        }
        
        internal static string CubicCentimeters {
            get {
                return ResourceManager.GetString("CubicCentimeters", resourceCulture);
            }
        }
        
        internal static string CubicFeet {
            get {
                return ResourceManager.GetString("CubicFeet", resourceCulture);
            }
        }
        
        internal static string CubicInches {
            get {
                return ResourceManager.GetString("CubicInches", resourceCulture);
            }
        }
        
        internal static string CubicMeters {
            get {
                return ResourceManager.GetString("CubicMeters", resourceCulture);
            }
        }
        
        internal static string CubicYards {
            get {
                return ResourceManager.GetString("CubicYards", resourceCulture);
            }
        }
        
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        internal static string Delisle {
            get {
                return ResourceManager.GetString("Delisle", resourceCulture);
            }
        }
        
        internal static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        internal static string Fathoms {
            get {
                return ResourceManager.GetString("Fathoms", resourceCulture);
            }
        }
        
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        internal static string GallonsUK {
            get {
                return ResourceManager.GetString("GallonsUK", resourceCulture);
            }
        }
        
        internal static string GallonsUS {
            get {
                return ResourceManager.GetString("GallonsUS", resourceCulture);
            }
        }
        
        internal static string Grams {
            get {
                return ResourceManager.GetString("Grams", resourceCulture);
            }
        }
        
        internal static string Hectares {
            get {
                return ResourceManager.GetString("Hectares", resourceCulture);
            }
        }
        
        internal static string Horsepower {
            get {
                return ResourceManager.GetString("Horsepower", resourceCulture);
            }
        }
        
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        internal static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        internal static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        internal static string Kilograms {
            get {
                return ResourceManager.GetString("Kilograms", resourceCulture);
            }
        }
        
        internal static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        internal static string Kilowatts {
            get {
                return ResourceManager.GetString("Kilowatts", resourceCulture);
            }
        }
        
        internal static string LengthConverterName {
            get {
                return ResourceManager.GetString("LengthConverterName", resourceCulture);
            }
        }
        
        internal static string LightYears {
            get {
                return ResourceManager.GetString("LightYears", resourceCulture);
            }
        }
        
        internal static string Litres {
            get {
                return ResourceManager.GetString("Litres", resourceCulture);
            }
        }
        
        internal static string MassConverterName {
            get {
                return ResourceManager.GetString("MassConverterName", resourceCulture);
            }
        }
        
        internal static string Metres {
            get {
                return ResourceManager.GetString("Metres", resourceCulture);
            }
        }
        
        internal static string Micrometers {
            get {
                return ResourceManager.GetString("Micrometers", resourceCulture);
            }
        }
        
        internal static string Microseconds {
            get {
                return ResourceManager.GetString("Microseconds", resourceCulture);
            }
        }
        
        internal static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        internal static string Milligrams {
            get {
                return ResourceManager.GetString("Milligrams", resourceCulture);
            }
        }
        
        internal static string Millimeters {
            get {
                return ResourceManager.GetString("Millimeters", resourceCulture);
            }
        }
        
        internal static string Milliseconds {
            get {
                return ResourceManager.GetString("Milliseconds", resourceCulture);
            }
        }
        
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        internal static string Nanometres {
            get {
                return ResourceManager.GetString("Nanometres", resourceCulture);
            }
        }
        
        internal static string NauticalMiles {
            get {
                return ResourceManager.GetString("NauticalMiles", resourceCulture);
            }
        }
        
        internal static string Newton {
            get {
                return ResourceManager.GetString("Newton", resourceCulture);
            }
        }
        
        internal static string Parsecs {
            get {
                return ResourceManager.GetString("Parsecs", resourceCulture);
            }
        }
        
        internal static string PintsUK {
            get {
                return ResourceManager.GetString("PintsUK", resourceCulture);
            }
        }
        
        internal static string PintsUS {
            get {
                return ResourceManager.GetString("PintsUS", resourceCulture);
            }
        }
        
        internal static string Pounds {
            get {
                return ResourceManager.GetString("Pounds", resourceCulture);
            }
        }
        
        internal static string PowerConverterName {
            get {
                return ResourceManager.GetString("PowerConverterName", resourceCulture);
            }
        }
        
        internal static string Rankine {
            get {
                return ResourceManager.GetString("Rankine", resourceCulture);
            }
        }
        
        internal static string Réaumur {
            get {
                return ResourceManager.GetString("Réaumur", resourceCulture);
            }
        }
        
        internal static string Rods {
            get {
                return ResourceManager.GetString("Rods", resourceCulture);
            }
        }
        
        internal static string Rømer {
            get {
                return ResourceManager.GetString("Rømer", resourceCulture);
            }
        }
        
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        internal static string Slugs {
            get {
                return ResourceManager.GetString("Slugs", resourceCulture);
            }
        }
        
        internal static string SquareCentimeters {
            get {
                return ResourceManager.GetString("SquareCentimeters", resourceCulture);
            }
        }
        
        internal static string SquareFeet {
            get {
                return ResourceManager.GetString("SquareFeet", resourceCulture);
            }
        }
        
        internal static string SquareInches {
            get {
                return ResourceManager.GetString("SquareInches", resourceCulture);
            }
        }
        
        internal static string SquareKilometers {
            get {
                return ResourceManager.GetString("SquareKilometers", resourceCulture);
            }
        }
        
        internal static string SquareMetres {
            get {
                return ResourceManager.GetString("SquareMetres", resourceCulture);
            }
        }
        
        internal static string SquareMiles {
            get {
                return ResourceManager.GetString("SquareMiles", resourceCulture);
            }
        }
        
        internal static string SquareMillimeters {
            get {
                return ResourceManager.GetString("SquareMillimeters", resourceCulture);
            }
        }
        
        internal static string SquareYards {
            get {
                return ResourceManager.GetString("SquareYards", resourceCulture);
            }
        }
        
        internal static string TemperatureConverterName {
            get {
                return ResourceManager.GetString("TemperatureConverterName", resourceCulture);
            }
        }
        
        internal static string TimeConverterName {
            get {
                return ResourceManager.GetString("TimeConverterName", resourceCulture);
            }
        }
        
        internal static string Tonne {
            get {
                return ResourceManager.GetString("Tonne", resourceCulture);
            }
        }
        
        internal static string VolumeConverterName {
            get {
                return ResourceManager.GetString("VolumeConverterName", resourceCulture);
            }
        }
        
        internal static string Watts {
            get {
                return ResourceManager.GetString("Watts", resourceCulture);
            }
        }
        
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        internal static string Yards {
            get {
                return ResourceManager.GetString("Yards", resourceCulture);
            }
        }
        
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
