//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFunc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xFunc.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutButtonHeader {
            get {
                return ResourceManager.GetString("AboutButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the about window.
        /// </summary>
        public static string AboutButtonToolTip {
            get {
                return ResourceManager.GetString("AboutButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional.
        /// </summary>
        public static string AdditionalLogicExpanderHeader {
            get {
                return ResourceManager.GetString("AdditionalLogicExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional.
        /// </summary>
        public static string AdditionalMathExpanderHeader {
            get {
                return ResourceManager.GetString("AdditionalMathExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angles.
        /// </summary>
        public static string AnglesGroupHeader {
            get {
                return ResourceManager.GetString("AnglesGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer:.
        /// </summary>
        public static string AnswerTextBox {
            get {
                return ResourceManager.GetString("AnswerTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{1}&apos; was assigned to the variable &apos;{0}&apos;..
        /// </summary>
        public static string AssignVariable {
            get {
                return ResourceManager.GetString("AssignVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dmitry Kischenko.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string AuthorTextBox {
            get {
                return ResourceManager.GetString("AuthorTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise.
        /// </summary>
        public static string BitwiseExpanderHeader {
            get {
                return ResourceManager.GetString("BitwiseExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearButtonHeader {
            get {
                return ResourceManager.GetString("ClearButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all expressions..
        /// </summary>
        public static string ClearScreenTipText {
            get {
                return ResourceManager.GetString("ClearScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearScreenTipTitle {
            get {
                return ResourceManager.GetString("ClearScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string ClipboardGroupHeader {
            get {
                return ResourceManager.GetString("ClipboardGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string cm {
            get {
                return ResourceManager.GetString("cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants.
        /// </summary>
        public static string ConstantsExpanderHeader {
            get {
                return ResourceManager.GetString("ConstantsExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &quot;Answer&quot;.
        /// </summary>
        public static string CopyAnswerMenuItem {
            get {
                return ResourceManager.GetString("CopyAnswerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyButtonHeader {
            get {
                return ResourceManager.GetString("CopyButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &quot;Expression&quot;.
        /// </summary>
        public static string CopyExpressionMenuItem {
            get {
                return ResourceManager.GetString("CopyExpressionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the selected text.
        /// </summary>
        public static string CopyScreenTipText {
            get {
                return ResourceManager.GetString("CopyScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl+C).
        /// </summary>
        public static string CopyScreenTipTitle {
            get {
                return ResourceManager.GetString("CopyScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CutButtonHeader {
            get {
                return ResourceManager.GetString("CutButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut the selected text.
        /// </summary>
        public static string CutScreenTipText {
            get {
                return ResourceManager.GetString("CutScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut (Ctrl+X).
        /// </summary>
        public static string CutScreenTipTitle {
            get {
                return ResourceManager.GetString("CutScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dergee.
        /// </summary>
        public static string DegreeButtonHeader {
            get {
                return ResourceManager.GetString("DegreeButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use degrees as a unit of angle measure.
        /// </summary>
        public static string DegreeScreenTipText {
            get {
                return ResourceManager.GetString("DegreeScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree (Ctrl+Alt+D).
        /// </summary>
        public static string DegreeScreenTipTitle {
            get {
                return ResourceManager.GetString("DegreeScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteExpButtonHeader {
            get {
                return ResourceManager.GetString("DeleteExpButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected expression.
        /// </summary>
        public static string DeleteExpScreenTipText {
            get {
                return ResourceManager.GetString("DeleteExpScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteExpScreenTipTitle {
            get {
                return ResourceManager.GetString("DeleteExpScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMenuItem {
            get {
                return ResourceManager.GetString("DeleteMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression List.
        /// </summary>
        public static string ExpListGroupHeader {
            get {
                return ResourceManager.GetString("ExpListGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressions:.
        /// </summary>
        public static string ExpressionsTextBox {
            get {
                return ResourceManager.GetString("ExpressionsTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression:.
        /// </summary>
        public static string ExpressionTextBox {
            get {
                return ResourceManager.GetString("ExpressionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string FontGroupHeader {
            get {
                return ResourceManager.GetString("FontGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string FontSizeSpinner {
            get {
                return ResourceManager.GetString("FontSizeSpinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradian.
        /// </summary>
        public static string GradianButtonHeader {
            get {
                return ResourceManager.GetString("GradianButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use gradians as a unit of angle measure.
        /// </summary>
        public static string GradianScreenTipText {
            get {
                return ResourceManager.GetString("GradianScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradian (Ctrl+Alt+G).
        /// </summary>
        public static string GradianScreenTipTitle {
            get {
                return ResourceManager.GetString("GradianScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphs.
        /// </summary>
        public static string GraphsTab {
            get {
                return ResourceManager.GetString("GraphsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page:.
        /// </summary>
        public static string HomePageTextBox {
            get {
                return ResourceManager.GetString("HomePageTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeRibbonTabHeader {
            get {
                return ResourceManager.GetString("HomeRibbonTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic.
        /// </summary>
        public static string HyperbolicExpanderHeader {
            get {
                return ResourceManager.GetString("HyperbolicExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perhaps, variables have entered incorrectly..
        /// </summary>
        public static string IndexOutOfRangeExceptionError {
            get {
                return ResourceManager.GetString("IndexOutOfRangeExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string InsertRibbonTab {
            get {
                return ResourceManager.GetString("InsertRibbonTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic Expressions.
        /// </summary>
        public static string LogicTab {
            get {
                return ResourceManager.GetString("LogicTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math Expressions.
        /// </summary>
        public static string MathTab {
            get {
                return ResourceManager.GetString("MathTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not supported..
        /// </summary>
        public static string NotSupportedOperationError {
            get {
                return ResourceManager.GetString("NotSupportedOperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers &amp; Arithmetic.
        /// </summary>
        public static string NumberAndArithmeticExpanderHeader {
            get {
                return ResourceManager.GetString("NumberAndArithmeticExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string PasteButtonHeader {
            get {
                return ResourceManager.GetString("PasteButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste text from clipboard.
        /// </summary>
        public static string PasteScreenTipText {
            get {
                return ResourceManager.GetString("PasteScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste (Ctrl+V).
        /// </summary>
        public static string PasteScreenTipTitle {
            get {
                return ResourceManager.GetString("PasteScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radian.
        /// </summary>
        public static string RadianButtonHeader {
            get {
                return ResourceManager.GetString("RadianButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use radians as a unit of angle measure.
        /// </summary>
        public static string RadianScreenTipText {
            get {
                return ResourceManager.GetString("RadianScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radian (Ctrl+Alt+R).
        /// </summary>
        public static string RadianScreenTipTitle {
            get {
                return ResourceManager.GetString("RadianScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string RedoButtonHeader {
            get {
                return ResourceManager.GetString("RedoButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo the last change.
        /// </summary>
        public static string RedoScreenTipText {
            get {
                return ResourceManager.GetString("RedoScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo (Ctrl+Y).
        /// </summary>
        public static string RedoScreenTipTitle {
            get {
                return ResourceManager.GetString("RedoScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Grid.
        /// </summary>
        public static string ShowGridCheckBox {
            get {
                return ResourceManager.GetString("ShowGridCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standart.
        /// </summary>
        public static string StandartExpanderHeader {
            get {
                return ResourceManager.GetString("StandartExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Clipboard.
        /// </summary>
        public static string ToClipboardMenuItem {
            get {
                return ResourceManager.GetString("ToClipboardMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Input.
        /// </summary>
        public static string ToInputMenuItem {
            get {
                return ResourceManager.GetString("ToInputMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigonometric.
        /// </summary>
        public static string TrigonometricExpanderHeader {
            get {
                return ResourceManager.GetString("TrigonometricExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truth Table.
        /// </summary>
        public static string TruthTableTab {
            get {
                return ResourceManager.GetString("TruthTableTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; variable is removed..
        /// </summary>
        public static string UndefineVariable {
            get {
                return ResourceManager.GetString("UndefineVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string UndoButtonHeader {
            get {
                return ResourceManager.GetString("UndoButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo the last change.
        /// </summary>
        public static string UndoScreenTipText {
            get {
                return ResourceManager.GetString("UndoScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo (Ctrl+Z).
        /// </summary>
        public static string UndoScreenTipTitle {
            get {
                return ResourceManager.GetString("UndoScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable not found..
        /// </summary>
        public static string VariableNotFoundExceptionError {
            get {
                return ResourceManager.GetString("VariableNotFoundExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string VariablesGroupHeader {
            get {
                return ResourceManager.GetString("VariablesGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VersionTextBox {
            get {
                return ResourceManager.GetString("VersionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewRibbonTab {
            get {
                return ResourceManager.GetString("ViewRibbonTab", resourceCulture);
            }
        }
    }
}
