//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFunc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xFunc.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutButtonHeader {
            get {
                return ResourceManager.GetString("AboutButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the about window.
        /// </summary>
        public static string AboutButtonToolTip {
            get {
                return ResourceManager.GetString("AboutButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute value of &quot;x&quot;. Example: abs(-1).
        /// </summary>
        public static string AbsToolTip {
            get {
                return ResourceManager.GetString("AbsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional.
        /// </summary>
        public static string AdditionalLogicExpanderHeader {
            get {
                return ResourceManager.GetString("AdditionalLogicExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional.
        /// </summary>
        public static string AdditionalMathExpanderHeader {
            get {
                return ResourceManager.GetString("AdditionalMathExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise AND operation. This operation rounds a rational number. Example: x and y, x &amp; y.
        /// </summary>
        public static string AndToolTip {
            get {
                return ResourceManager.GetString("AndToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angles.
        /// </summary>
        public static string AnglesGroupHeader {
            get {
                return ResourceManager.GetString("AnglesGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Base.
        /// </summary>
        public static string AnswerBaseGroupHeader {
            get {
                return ResourceManager.GetString("AnswerBaseGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer:.
        /// </summary>
        public static string AnswerTextBox {
            get {
                return ResourceManager.GetString("AnswerTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse cosecant of a number. Example: arccsc(90) or arccosec(90).
        /// </summary>
        public static string ArccosecantToolTip {
            get {
                return ResourceManager.GetString("ArccosecantToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse cosine of a number. Example: arccos(90).
        /// </summary>
        public static string ArccosineToolTip {
            get {
                return ResourceManager.GetString("ArccosineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse cotangent of a number. Example: arccot(90) or arcctg(90).
        /// </summary>
        public static string ArccotangentToolTip {
            get {
                return ResourceManager.GetString("ArccotangentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse hyperbolic cosine of &quot;x&quot;. Example: arcosh(90) or arch(90).
        /// </summary>
        public static string ArcoshToolTip {
            get {
                return ResourceManager.GetString("ArcoshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse hyperbolic cotangent of &quot;x&quot;. Example: arcoth(90) or arcth(90).
        /// </summary>
        public static string ArcothToolTip {
            get {
                return ResourceManager.GetString("ArcothToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse hyperbolic cosecant of &quot;x&quot;. Example: arcsch(90).
        /// </summary>
        public static string ArcschToolTip {
            get {
                return ResourceManager.GetString("ArcschToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse secant of a number. Example: arcsec(90).
        /// </summary>
        public static string ArcsecantToolTip {
            get {
                return ResourceManager.GetString("ArcsecantToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse sine of a number. Example: arcsin(1).
        /// </summary>
        public static string ArcsineToolTip {
            get {
                return ResourceManager.GetString("ArcsineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse tangent of a number. Example: arctan(90) or arctg(90).
        /// </summary>
        public static string ArctangentToolTip {
            get {
                return ResourceManager.GetString("ArctangentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse hyperbolic secant of &quot;x&quot;. Example: arsech(90).
        /// </summary>
        public static string ArsechToolTip {
            get {
                return ResourceManager.GetString("ArsechToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse hyperbolic sine of &quot;x&quot;. Example: arsinh(90) or arsh(90).
        /// </summary>
        public static string ArsinhToolTip {
            get {
                return ResourceManager.GetString("ArsinhToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse hyperbolic tangent of &quot;x&quot;. Example: artanh(90) or arth(90).
        /// </summary>
        public static string ArtanhToolTip {
            get {
                return ResourceManager.GetString("ArtanhToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &apos;{1}&apos; was assigned to the function &apos;{0}&apos;..
        /// </summary>
        public static string AssignFunction {
            get {
                return ResourceManager.GetString("AssignFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{1}&apos; was assigned to the variable &apos;{0}&apos;..
        /// </summary>
        public static string AssignVariable {
            get {
                return ResourceManager.GetString("AssignVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dmitry Kischenko.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string AuthorTextBox {
            get {
                return ResourceManager.GetString("AuthorTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available..
        /// </summary>
        public static string AvailableUpdate {
            get {
                return ResourceManager.GetString("AvailableUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise.
        /// </summary>
        public static string BitwiseExpanderHeader {
            get {
                return ResourceManager.GetString("BitwiseExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearButtonHeader {
            get {
                return ResourceManager.GetString("ClearButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all expressions..
        /// </summary>
        public static string ClearScreenTipText {
            get {
                return ResourceManager.GetString("ClearScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearScreenTipTitle {
            get {
                return ResourceManager.GetString("ClearScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string ClipboardGroupHeader {
            get {
                return ResourceManager.GetString("ClipboardGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string cm {
            get {
                return ResourceManager.GetString("cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants.
        /// </summary>
        public static string ConstantsExpanderHeader {
            get {
                return ResourceManager.GetString("ConstantsExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &quot;Answer&quot;.
        /// </summary>
        public static string CopyAnswerMenuItem {
            get {
                return ResourceManager.GetString("CopyAnswerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyButtonHeader {
            get {
                return ResourceManager.GetString("CopyButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &quot;Expression&quot;.
        /// </summary>
        public static string CopyExpressionMenuItem {
            get {
                return ResourceManager.GetString("CopyExpressionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the selected text.
        /// </summary>
        public static string CopyScreenTipText {
            get {
                return ResourceManager.GetString("CopyScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl+C).
        /// </summary>
        public static string CopyScreenTipTitle {
            get {
                return ResourceManager.GetString("CopyScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosecant of a number. Example: csc(90) or cosec(90).
        /// </summary>
        public static string CosecantToolTip {
            get {
                return ResourceManager.GetString("CosecantToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic cosine of &quot;x&quot;. Example: cosh(90) or ch(90).
        /// </summary>
        public static string CoshToolTip {
            get {
                return ResourceManager.GetString("CoshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosine of a number. Example: cos(90).
        /// </summary>
        public static string CosineToolTip {
            get {
                return ResourceManager.GetString("CosineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotangent of a number. Example: cot(90) or ctg(90).
        /// </summary>
        public static string CotangentToolTip {
            get {
                return ResourceManager.GetString("CotangentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic cotangent of &quot;x&quot;. Example: coth(90) or cth(90).
        /// </summary>
        public static string CothToolTip {
            get {
                return ResourceManager.GetString("CothToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic cosecant of &quot;x&quot;. Example: csch(90).
        /// </summary>
        public static string CschToolTip {
            get {
                return ResourceManager.GetString("CschToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CutButtonHeader {
            get {
                return ResourceManager.GetString("CutButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut the selected text.
        /// </summary>
        public static string CutScreenTipText {
            get {
                return ResourceManager.GetString("CutScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut (Ctrl+X).
        /// </summary>
        public static string CutScreenTipTitle {
            get {
                return ResourceManager.GetString("CutScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigns the value to specified variable or creates an user-function. Example: x := 1, f(x) := sin(x).
        /// </summary>
        public static string DefToolTip {
            get {
                return ResourceManager.GetString("DefToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dergee.
        /// </summary>
        public static string DegreeButtonHeader {
            get {
                return ResourceManager.GetString("DegreeButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use degrees as a unit of angle measure.
        /// </summary>
        public static string DegreeScreenTipText {
            get {
                return ResourceManager.GetString("DegreeScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree (Ctrl+Alt+D).
        /// </summary>
        public static string DegreeScreenTipTitle {
            get {
                return ResourceManager.GetString("DegreeScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteExpButtonHeader {
            get {
                return ResourceManager.GetString("DeleteExpButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected expression.
        /// </summary>
        public static string DeleteExpScreenTipText {
            get {
                return ResourceManager.GetString("DeleteExpScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteExpScreenTipTitle {
            get {
                return ResourceManager.GetString("DeleteExpScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMenuItem {
            get {
                return ResourceManager.GetString("DeleteMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression List.
        /// </summary>
        public static string ExpListGroupHeader {
            get {
                return ResourceManager.GetString("ExpListGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressions:.
        /// </summary>
        public static string ExpressionsTextBox {
            get {
                return ResourceManager.GetString("ExpressionsTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression:.
        /// </summary>
        public static string ExpressionTextBox {
            get {
                return ResourceManager.GetString("ExpressionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FuncNameHeader {
            get {
                return ResourceManager.GetString("FuncNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the window with all entered functions..
        /// </summary>
        public static string FuncScreenTitText {
            get {
                return ResourceManager.GetString("FuncScreenTitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string FuncScreenTitTitle {
            get {
                return ResourceManager.GetString("FuncScreenTitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string FunctionButtonHeader {
            get {
                return ResourceManager.GetString("FunctionButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string FunctionsTitle {
            get {
                return ResourceManager.GetString("FunctionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string FuncValueHeader {
            get {
                return ResourceManager.GetString("FuncValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradian.
        /// </summary>
        public static string GradianButtonHeader {
            get {
                return ResourceManager.GetString("GradianButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use gradians as a unit of angle measure.
        /// </summary>
        public static string GradianScreenTipText {
            get {
                return ResourceManager.GetString("GradianScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradian (Ctrl+Alt+G).
        /// </summary>
        public static string GradianScreenTipTitle {
            get {
                return ResourceManager.GetString("GradianScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphs.
        /// </summary>
        public static string GraphsTab {
            get {
                return ResourceManager.GetString("GraphsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page:.
        /// </summary>
        public static string HomePageTextBox {
            get {
                return ResourceManager.GetString("HomePageTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeRibbonTabHeader {
            get {
                return ResourceManager.GetString("HomeRibbonTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic.
        /// </summary>
        public static string HyperbolicExpanderHeader {
            get {
                return ResourceManager.GetString("HyperbolicExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perhaps, variables have entered incorrectly..
        /// </summary>
        public static string IndexOutOfRangeExceptionError {
            get {
                return ResourceManager.GetString("IndexOutOfRangeExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarithm to base 10 of &quot;x&quot;. Example: lg(3).
        /// </summary>
        public static string LgToolTip {
            get {
                return ResourceManager.GetString("LgToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural logarithm of &quot;x&quot;. Example: ln(10).
        /// </summary>
        public static string LnToolTip {
            get {
                return ResourceManager.GetString("LnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic Expressions.
        /// </summary>
        public static string LogicTab {
            get {
                return ResourceManager.GetString("LogicTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarigthm to base &quot;y&quot; of &quot;x&quot;. Example: log(2, 4).
        /// </summary>
        public static string LogToolTip {
            get {
                return ResourceManager.GetString("LogToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math Expressions.
        /// </summary>
        public static string MathTab {
            get {
                return ResourceManager.GetString("MathTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not supported..
        /// </summary>
        public static string NotSupportedOperationError {
            get {
                return ResourceManager.GetString("NotSupportedOperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise NOT operation. This operation rounds a rational number. Example: not(3).
        /// </summary>
        public static string NotToolTip {
            get {
                return ResourceManager.GetString("NotToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nth root of &quot;x&quot;. Example: root(27, 3).
        /// </summary>
        public static string NthRootToolTip {
            get {
                return ResourceManager.GetString("NthRootToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers &amp; Arithmetic.
        /// </summary>
        public static string NumberAndArithmeticExpanderHeader {
            get {
                return ResourceManager.GetString("NumberAndArithmeticExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise OR operation. This operation rounds a rational number. Example: x or y, x | y.
        /// </summary>
        public static string OrToolTip {
            get {
                return ResourceManager.GetString("OrToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression Parameters.
        /// </summary>
        public static string ParamGroupHeader {
            get {
                return ResourceManager.GetString("ParamGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string PasteButtonHeader {
            get {
                return ResourceManager.GetString("PasteButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste text from clipboard.
        /// </summary>
        public static string PasteScreenTipText {
            get {
                return ResourceManager.GetString("PasteScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste (Ctrl+V).
        /// </summary>
        public static string PasteScreenTipTitle {
            get {
                return ResourceManager.GetString("PasteScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;x&quot; raised to the power of 2. Example: 7^2.
        /// </summary>
        public static string PowerOfTwoToolTip {
            get {
                return ResourceManager.GetString("PowerOfTwoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;x&quot; raised to the power of &quot;y&quot;. Example: 7^4.
        /// </summary>
        public static string PowerOfYToolTip {
            get {
                return ResourceManager.GetString("PowerOfYToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radian.
        /// </summary>
        public static string RadianButtonHeader {
            get {
                return ResourceManager.GetString("RadianButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use radians as a unit of angle measure.
        /// </summary>
        public static string RadianScreenTipText {
            get {
                return ResourceManager.GetString("RadianScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radian (Ctrl+Alt+R).
        /// </summary>
        public static string RadianScreenTipTitle {
            get {
                return ResourceManager.GetString("RadianScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string RedoButtonHeader {
            get {
                return ResourceManager.GetString("RedoButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo the last change.
        /// </summary>
        public static string RedoScreenTipText {
            get {
                return ResourceManager.GetString("RedoScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo (Ctrl+Y).
        /// </summary>
        public static string RedoScreenTipTitle {
            get {
                return ResourceManager.GetString("RedoScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secant of a number. Example: sec(90).
        /// </summary>
        public static string SecantToolTip {
            get {
                return ResourceManager.GetString("SecantToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic secant of &quot;x&quot;. Example: sech(90).
        /// </summary>
        public static string SechToolTip {
            get {
                return ResourceManager.GetString("SechToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Grid.
        /// </summary>
        public static string ShowGridCheckBox {
            get {
                return ResourceManager.GetString("ShowGridCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplifies the specified expression. Example: simplify(arcsin(sin(x))).
        /// </summary>
        public static string SimplifyToolTip {
            get {
                return ResourceManager.GetString("SimplifyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine of a number. Example: sin(90).
        /// </summary>
        public static string SineToolTip {
            get {
                return ResourceManager.GetString("SineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic sine of &quot;x&quot;. Example: sinh(90) or sh(90).
        /// </summary>
        public static string SinhToolTip {
            get {
                return ResourceManager.GetString("SinhToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square root of &quot;x&quot;. Example: sqrt(9).
        /// </summary>
        public static string SquareRootToolTip {
            get {
                return ResourceManager.GetString("SquareRootToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standart.
        /// </summary>
        public static string StandartExpanderHeader {
            get {
                return ResourceManager.GetString("StandartExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangent of a number. Example: tan(90) or tg(90).
        /// </summary>
        public static string TangentToolTip {
            get {
                return ResourceManager.GetString("TangentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic tangent of &quot;x&quot;. Example: tanh(90) or th(90).
        /// </summary>
        public static string TanhToolTip {
            get {
                return ResourceManager.GetString("TanhToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Clipboard.
        /// </summary>
        public static string ToClipboardMenuItem {
            get {
                return ResourceManager.GetString("ToClipboardMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Input.
        /// </summary>
        public static string ToInputMenuItem {
            get {
                return ResourceManager.GetString("ToInputMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigonometric.
        /// </summary>
        public static string TrigonometricExpanderHeader {
            get {
                return ResourceManager.GetString("TrigonometricExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truth Table.
        /// </summary>
        public static string TruthTableTab {
            get {
                return ResourceManager.GetString("TruthTableTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; function is removed..
        /// </summary>
        public static string UndefineFunction {
            get {
                return ResourceManager.GetString("UndefineFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; variable is removed..
        /// </summary>
        public static string UndefineVariable {
            get {
                return ResourceManager.GetString("UndefineVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the specified variable or user-function. Example: undef(x).
        /// </summary>
        public static string UndefToolTip {
            get {
                return ResourceManager.GetString("UndefToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string UndoButtonHeader {
            get {
                return ResourceManager.GetString("UndoButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo the last change.
        /// </summary>
        public static string UndoScreenTipText {
            get {
                return ResourceManager.GetString("UndoScreenTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo (Ctrl+Z).
        /// </summary>
        public static string UndoScreenTipTitle {
            get {
                return ResourceManager.GetString("UndoScreenTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable not found..
        /// </summary>
        public static string VariableNotFoundExceptionError {
            get {
                return ResourceManager.GetString("VariableNotFoundExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string VariablesButtonHeader {
            get {
                return ResourceManager.GetString("VariablesButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string VariablesTitle {
            get {
                return ResourceManager.GetString("VariablesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string VarNameHeader {
            get {
                return ResourceManager.GetString("VarNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the window with all entered variables..
        /// </summary>
        public static string VarScreenTitText {
            get {
                return ResourceManager.GetString("VarScreenTitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string VarScreenTitTitle {
            get {
                return ResourceManager.GetString("VarScreenTitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string VarValueHeader {
            get {
                return ResourceManager.GetString("VarValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VersionTextBox {
            get {
                return ResourceManager.GetString("VersionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise XOR operation. This operation rounds a rational number. Example: x xor y.
        /// </summary>
        public static string XOrToolTip {
            get {
                return ResourceManager.GetString("XOrToolTip", resourceCulture);
            }
        }
    }
}
