trigger:
  batch: true
  branches:
    include:
      - master
      - dev

pr:
  autoCancel: true
  branches:
    include:
      - master
      - dev

jobs:
  - job: xFunc
    pool:
      vmImage: 'windows-latest'

    variables:
      uiSolution: 'xFunc/xFunc.UI.sln'
      solution: 'xFunc.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET 5'
      inputs:
        packageType: 'sdk'
        version: '5.0.x'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        projects: '$(solution)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: '$(solution)'
        arguments: '-c $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: test
        projects: '$(solution)'
        arguments: '--nologo --no-build -c $(buildConfiguration) -p:CollectCoverage=true -p:CoverletOutput=$(Build.SourcesDirectory)/coverage/'
        publishTestResults: true

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Build.SourcesDirectory)/coverage/coverage.cobertura.xml'
        pathToSources: '$(Build.SourcesDirectory)/coverage/'
        failIfCoverageEmpty: true

    - bash: bash <(curl -s https://codecov.io/bash) -Z -f "./coverage/coverage.cobertura.xml"
      displayName: 'Publish to Codecov'
      env:
        CODECOV_TOKEN: $(CODECOV_TOKEN)

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        projects: '$(uiSolution)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: '$(uiSolution)'
        arguments: '-c $(buildConfiguration)'
    
    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack'
      inputs:
        command: 'pack'
        packagesToPack: '$(solution)'
        outputDir: 'nupkgs'
        nobuild: true
        includesymbols: true

    - task: PublishPipelineArtifact@1
      inputs:
        path: xFunc.Maths/bin/Release/netstandard2.1
        artifact: xFunc.Maths

    - task: PublishPipelineArtifact@1
      inputs:
        path: xFunc.UnitConverters/bin/Release/netstandard2.1
        artifact: xFunc.UnitConverters

    - task: PublishPipelineArtifact@1
      inputs:
        path: nupkgs
        artifact: NuGet Packages

    - task: PublishPipelineArtifact@1
      inputs:
        path: xFunc/bin/Release/netcoreapp3.1
        artifact: xFunc.UI (.NET Core 3.1)

    - task: PublishPipelineArtifact@1
      inputs:
        path: xFunc/bin/Release/net5.0-windows
        artifact: xFunc.UI (.NET 5)