trigger:
  batch: true
  branches:
    include:
      - master
      - dev

pr:
  autoCancel: true
  branches:
    include:
      - master
      - dev

jobs:
  - job: xFunc
    pool:
      vmImage: 'windows-latest'

    variables:
      uiSolution: 'xFunc/xFunc.UI.sln'
      solution: 'xFunc.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - script: echo '##vso[task.setvariable variable=nupkgVersion]$(defaultPackageVersion)
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

    - script: echo '##vso[task.setvariable variable=nupkgVersion]$(defaultPackageVersion)-preview$(Build.BuildNumber)
      condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        projects: '$(solution)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: '$(solution)'
        arguments: '-c $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: test
        projects: '$(solution)'
        arguments: '-c $(buildConfiguration) -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput="$(Build.SourcesDirectory)/coverage/" -p:ExcludeByAttribute="ExcludeFromCodeCoverage" -p:Include="[xFunc.*]*" -p:Exclude="[xFunc.Tests*]*%2c[xFunc.*]*.Resource%2c[xFunc.*]*Exception" -p:Threshold=90 -p:ThresholdStat=total'
        publishTestResults: true

    - task: CmdLine@2
      inputs:
        script: 'dotnet reportgenerator -reports:"$(Build.SourcesDirectory)/coverage/coverage.cobertura.xml" -targetdir:"$(Build.SourcesDirectory)/coverage/" -reporttypes:HtmlInline_AzurePipelines'
        workingDirectory: 'xFunc.Tests'
        failOnStderr: true

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Build.SourcesDirectory)/coverage/coverage.cobertura.xml'
        pathToSources: '$(Build.SourcesDirectory)/coverage/'
        failIfCoverageEmpty: true

    - task: CmdLine@2
      inputs:
        script: '"%userprofile%/.nuget/packages/codecov/1.10.0/tools/codecov.exe" -f "$(Build.SourcesDirectory)/coverage/coverage.cobertura.xml" -t $(CODECOV_TOKEN)'
        failOnStderr: true

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        projects: '$(uiSolution)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: '$(uiSolution)'
        arguments: '-c $(buildConfiguration)'
    
    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack'
      inputs:
        command: 'pack'
        packagesToPack: '$(solution)'
        outputDir: 'nupkgs'
        nobuild: true
        includesymbols: true
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'nupkgVersion'

    - task: PublishPipelineArtifact@1
      inputs:
        path: xFunc.Maths/bin/Release/netstandard2.1
        artifact: xFunc.Maths

    - task: PublishPipelineArtifact@1
      inputs:
        path: xFunc.UnitConverters/bin/Release/netstandard2.1
        artifact: xFunc.UnitConverters

    - task: PublishPipelineArtifact@1
      inputs:
        path: nupkgs
        artifact: NuGet Packages

    - task: PublishPipelineArtifact@1
      inputs:
        path: xFunc/bin/Release/netcoreapp3.1
        artifact: xFunc.UI